version: "2"
services:

  mosquitto:
    image: eclipse-mosquitto:1.6.15
    restart: always
    ports:
      - "1883:1883"

  wavplayeralsa:
    image: blumamir/wavplayeralsa
    restart: always
    ports:
      - "8080:80"
      - "9002:9002"
    volumes:
      - /home/pi/Music:/wav_files
    devices:
      - /dev/snd
    depends_on: 
      - "mosquitto"
    
    entrypoint:
      - ./wavplayeralsa
      - -d
      - /wav_files
      - --http_listen_port
      - "80"
      - --ws_listen_port
      - "9002"
      - --mqtt_host
      - "10.0.0.200"
      - --mqtt_port
      - "1883"

  timesyncserver:
    image: blumamir/time-sync-server
    restart: always
    ports:
      - "12321:12321/udp"
