{
 "title": "All things",
 "description": "A dashboard displaying all the things information",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "thingList",
    "query": "esp32thing,esp32thing2,lifas4,brain7"
   }
  ]
 },
 "panels": [
  {
   "title": "$thingList uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "repeat": "thingList",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wifi_status",
     "query": "SELECT last(\"uptime\") / 1000 AS \"seconds\" FROM \"wifi_status\" WHERE (\"device\" =~ /^$thingList$/) AND $timeFilter GROUP BY time($__interval), \"device\" fill(null)",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" },
       { "params": [ "seconds" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$thingList$/" }
     ]
    }
   ]
  },
  {
   "title": "Wifi signal avg",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wifi_status",
     "select": [
      [
       { "params": [ "rssi" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wifi signals minimum values",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 5, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "wifi_status",
     "select": [
      [
       { "params": [ "rssi" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alive table",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "wifi_status",
     "query": "SELECT count(\"uptime\") FROM \"wifi_status\" WHERE (\"device\" =~ /^$thingList$/) AND time > (now() - 30s) AND time < now() GROUP BY time(60s), \"device\" fill(0)",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$thingList$/" }
     ]
    }
   ]
  },
  {
   "title": "dashboards",
   "type": "dashlist",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wifi_status",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wifi signal min",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wifi_status",
     "select": [
      [
       { "params": [ "rssi" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Free heap avg",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wifi_status",
     "select": [
      [
       { "params": [ "free heap" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}